language: r
cache: packages
env:
  global:
  - secure: TzuzjNRNjV+dO8RX2ckccyGEThP6c3X2n8vqmRX1sATAGIuvuNbalZ/Eh97CkKBnwssJ+aObVVQk1PjtOgk2OTpMxNT8Y8avcuW6wIE1l2c0SHhBnDPAozASaagAFl5zzV3fpaqjdQHn3R1JZTL+MP7j1Xe3k4x+x42HIebQ8PKse6I0mEQqsxDNHkPATBLSf4O3tGIn9v90dAd+gwI0++eO6fHN22emBHid/0FqcMQlnoPcKH8uTBktFNRwRvQVPb1xtlG5Ab4voIA4g0mjTUgDpYCru9bFEBQV3yoOS//DnvQSXiGvX932m1MDTFjfc6yaDeiEldsSSFN2HViKLa8GDryJreTq6zmCRHxys45aY3fBee6/0gUCcB6EVnacXH89I/ApVU9UQe+rzdcvmWsMfAnWY86FM7Ml2FFH6Fbpy0IbQKJXQ2Db+9cCqEkru1JTn9uF9LObWeDV0tEWVY1ekRwgOkIWdznsNopRyw/1g4Dn+N4GoFByuoBcrO2lJcRjwGBKZcTIXPFbVwXF7Cp24yQkC7EU0RA718nEWimnEE7eAmyv85+LBfc8J5DC6ah7nySYAJ8aPENvubNVVaOSkr1O6BIATv7jjzhgP5SjVuiqzHa7KZfwDz2ZQhcdgmf1tONiS90ER94oS0UyuRTTgc40gKr/4xqxwlGbYE8=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
